// Mocks generated by Mockito 5.4.6 from annotations
// in cocinando_con_flow/test/feature/busqueda/domain/bloc/busqueda_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cocinando_con_flow/src/feature/busqueda/domain/repository/busqueda_repository.dart'
    as _i2;
import 'package:cocinando_con_flow/src/shared/domain/entities/entities.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BusquedaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBusquedaRepository extends _i1.Mock
    implements _i2.BusquedaRepository {
  MockBusquedaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RecetaEntity>> buscarRecetasPorNombre(String? nombre) =>
      (super.noSuchMethod(
        Invocation.method(
          #buscarRecetasPorNombre,
          [nombre],
        ),
        returnValue:
            _i3.Future<List<_i4.RecetaEntity>>.value(<_i4.RecetaEntity>[]),
      ) as _i3.Future<List<_i4.RecetaEntity>>);

  @override
  _i3.Future<void> agregarAFavoritos(String? recetaId) => (super.noSuchMethod(
        Invocation.method(
          #agregarAFavoritos,
          [recetaId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> quitarDeFavoritos(String? recetaId) => (super.noSuchMethod(
        Invocation.method(
          #quitarDeFavoritos,
          [recetaId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> esFavorito(String? recetaId) => (super.noSuchMethod(
        Invocation.method(
          #esFavorito,
          [recetaId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
