// Mocks generated by Mockito 5.4.6 from annotations
// in cocinando_con_flow/test/feature/detalle/data/repository/detalle_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cocinando_con_flow/src/feature/detalle/data/services/detalle_api_service.dart'
    as _i2;
import 'package:cocinando_con_flow/src/shared/data/models/models.dart' as _i4;
import 'package:cocinando_con_flow/src/shared/storage/local/local_favorites_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DetalleApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetalleApiService extends _i1.Mock implements _i2.DetalleApiService {
  MockDetalleApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.RecetaModel?> obtenerRecetaPorId(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #obtenerRecetaPorId,
          [id],
        ),
        returnValue: _i3.Future<_i4.RecetaModel?>.value(),
      ) as _i3.Future<_i4.RecetaModel?>);
}

/// A class which mocks [LocalFavoritesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalFavoritesService extends _i1.Mock
    implements _i5.LocalFavoritesService {
  MockLocalFavoritesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Set<String>> obtenerFavoritos() => (super.noSuchMethod(
        Invocation.method(
          #obtenerFavoritos,
          [],
        ),
        returnValue: _i3.Future<Set<String>>.value(<String>{}),
      ) as _i3.Future<Set<String>>);

  @override
  _i3.Future<bool> esFavorito(String? id) => (super.noSuchMethod(
        Invocation.method(
          #esFavorito,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> agregar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #agregar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> quitar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #quitar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
